create table if not exists public.birthdays (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slug text not null unique,
  data jsonb not null
);

alter table public.birthdays enable row level security;

drop policy if exists "Public can create birthday shares" on public.birthdays;
create policy "Public can create birthday shares"
  on public.birthdays for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Public can read birthday shares" on public.birthdays;
create policy "Public can read birthday shares"
  on public.birthdays for select
  to anon, authenticated
  using (true);

grant insert, select on public.birthdays to anon, authenticated;
